version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
    - 2.40.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: acorn
    versions:
    - 8.0.4
  - dependency-name: acorn-walk
    versions:
    - 8.0.0
